### ISSUE TITLE
Migrate front end styles to tailwind

### ISSUE THREAD

**Issue by RidhaChowdhury** [LeetCopilot/LeetCopilot#13]
Tech Description:
SCSS (Sassy CSS) and SASS (Syntactically Awesome Stylesheets) are extensions of the CSS language that bring features like variables, nested rules, and mixins to the traditional CSS. These tools allow for cleaner, more maintainable, and more organized stylesheets. In addition, they offer enhanced functionality that is not possible with vanilla CSS.

Task:
Migrate our current front-end styles to utilize SCSS/SASS, streamlining our stylesheets and enabling us to take advantage of the advanced capabilities of SCSS/SASS. This will help in improving our code readability, maintainability, and ensure consistency across our application's styling.

Resources:
[2 min]How to implement SCSS in React:
https://www.youtube.com/watch?v=9F8bzIlgJ4g

[20 min] SCSS crashcourse:
https://www.youtube.com/watch?v=Zz6eOVaaelI

**Comment by ehedges03** [comment]
Switching this issue to instead be transitioning the front end to tailwind.
